In [45]:
#### from random import randint
from numpy import array
from numpy import argmax
from pandas import DataFrame
from pandas import concat

# generate a sequence of random numbers in [0, 99]
def generate_sequence(length=25):
	return [randint(0, 99) for _ in range(length)]

# one hot encode sequence
def one_hot_encode(sequence, n_unique=100):
	encoding = list()
	for value in sequence:
		vector = [0 for _ in range(n_unique)]
		vector[value] = 1
		encoding.append(vector)
	return array(encoding)

# decode a one hot encoded string
def one_hot_decode(encoded_seq):
	return [argmax(vector) for vector in encoded_seq]

# convert encoded sequence to supervised learning
def to_supervised(sequence, n_in, n_out):
	# create lag copies of the sequence
	df = DataFrame(sequence)
	df = concat([df.shift(n_in-i-1) for i in range(n_in)], axis=1)
	print("#####",df)
	# drop rows with missing values
	df.dropna(inplace=True)
	#print("--->",df)
	# specify columns for input and output pairs
	values = df.values
	#print("---<",values)
	width = sequence.shape[1]
	print("width:",width)
	X = values.reshape(len(values), n_in, width)
	y = values[:, 0:(n_out*width)].reshape(len(values), n_out, width)
	return X, y

# generate random sequence
sequence = generate_sequence()
print("SSSSSSS:",sequence)
# one hot encode
encoded = one_hot_encode(sequence)
print(encoded.shape)
# convert to X,y pairs
X,y = to_supervised(encoded, 20, 5)
print("X,y:",len(X),len(y))
# decode all pairs
for i in range(len(X)):
	print(one_hot_decode(X[i]), '=>', one_hot_decode(y[i]))

SSSSSSS: [16, 61, 38, 37, 57, 87, 88, 45, 11, 99, 72, 2, 81, 17, 65, 4, 50, 42, 86, 23, 27, 27, 44, 57, 38]
(25, 100)
#####      0    1    2    3    4    5    6    7    8    9  ...  90  91  92  93  94  \
0   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
1   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
2   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
3   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
4   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
5   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
6   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
7   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
12  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
13  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
14  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
15  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
16  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
17  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
18  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   0   0   0   0   0
19  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0   0   0   0   0
20  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0   0   0   0   0
21  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0   0   0   0   0
22  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0   0   0   0   0
23  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0   0   0   0   0
24  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0   0   0   0   0

    95  96  97  98  99
0    0   0   0   0   0
1    0   0   0   0   0
2    0   0   0   0   0
3    0   0   0   0   0
4    0   0   0   0   0
5    0   0   0   0   0
6    0   0   0   0   0
7    0   0   0   0   0
8    0   0   0   0   0
9    0   0   0   0   1
10   0   0   0   0   0
11   0   0   0   0   0
12   0   0   0   0   0
13   0   0   0   0   0
14   0   0   0   0   0
15   0   0   0   0   0
16   0   0   0   0   0
17   0   0   0   0   0
18   0   0   0   0   0
19   0   0   0   0   0
20   0   0   0   0   0
21   0   0   0   0   0
22   0   0   0   0   0
23   0   0   0   0   0
24   0   0   0   0   0

[25 rows x 2000 columns]
width: 100
X,y: 6 6
[16, 61, 38, 37, 57, 87, 88, 45, 11, 99, 72, 2, 81, 17, 65, 4, 50, 42, 86, 23] => [16, 61, 38, 37, 57]
[61, 38, 37, 57, 87, 88, 45, 11, 99, 72, 2, 81, 17, 65, 4, 50, 42, 86, 23, 27] => [61, 38, 37, 57, 87]
[38, 37, 57, 87, 88, 45, 11, 99, 72, 2, 81, 17, 65, 4, 50, 42, 86, 23, 27, 27] => [38, 37, 57, 87, 88]
[37, 57, 87, 88, 45, 11, 99, 72, 2, 81, 17, 65, 4, 50, 42, 86, 23, 27, 27, 44] => [37, 57, 87, 88, 45]
[57, 87, 88, 45, 11, 99, 72, 2, 81, 17, 65, 4, 50, 42, 86, 23, 27, 27, 44, 57] => [57, 87, 88, 45, 11]
[87, 88, 45, 11, 99, 72, 2, 81, 17, 65, 4, 50, 42, 86, 23, 27, 27, 44, 57, 38] => [87, 88, 45, 11, 99]